/*
 * Copyright 2020-2022 Yuntu Microelectronics Co., Ltd.
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/*!
 * @file linflexd_lin_irq.h
 * @version 1.4.1
 * @note CODE GENERATED BY TOOL AUTOMATICALLY, DO NOT MODIFY MANUALLY.
 */

#ifndef LINFlexD_LIN_IRQ_H
#define LINFlexD_LIN_IRQ_H

#include "linflexd_hw_access.h"

/*!
 * @brief Or'ed interrupt handler, implemented in driver c file.
 */
void LINFlexD_LIN_DRV_IRQHandler(uint32_t instance);

/*!
 * @brief Rx interrupt handler, implemented in driver c file.
 */
void LINFlexD_LIN_DRV_RxIRQHandler(uint32_t instance);

/*!
 * @brief Tx interrupt handler, implemented in driver c file.
 */
void LINFlexD_LIN_DRV_TxIRQHandler(uint32_t instance);

/*!
 * @brief Error interrupt handler, implemented in driver c file.
 */
void LINFlexD_LIN_DRV_ErrIRQHandler(uint32_t instance);

/*!
 * @brief ISR declarations - implemented in linflexd_lin_irq.c.
 */
#if defined(FEATURE_LINFlexD_ORED_INT_LINES) && (FEATURE_LINFlexD_ORED_INT_LINES == 1U)

    /* ISR declarations for rx/tx/err interrupts or'ed together */
    #if (LINFlexD_INSTANCE_COUNT > 0U)
    void LINFlexD0_LIN_IRQHandler(void);
    #endif
    #if (LINFlexD_INSTANCE_COUNT > 1U)
    void LINFlexD1_LIN_IRQHandler(void);
    #endif
    #if (LINFlexD_INSTANCE_COUNT > 2U)
    void LINFlexD2_LIN_IRQHandler(void);
    #endif
    #if (LINFlexD_INSTANCE_COUNT > 3U)
    void LINFlexD3_LIN_IRQHandler(void);
    #endif
    #if (LINFlexD_INSTANCE_COUNT > 4U)
    void LINFlexD4_LIN_IRQHandler(void);
    #endif
    #if (LINFlexD_INSTANCE_COUNT > 5U)
    void LINFlexD5_LIN_IRQHandler(void);
    #endif
    #if (LINFlexD_INSTANCE_COUNT > 6U)
    void LINFlexD6_LIN_IRQHandler(void);
    #endif
    #if (LINFlexD_INSTANCE_COUNT > 7U)
    void LINFlexD7_LIN_IRQHandler(void);
    #endif
    #if (LINFlexD_INSTANCE_COUNT > 8U)
    void LINFlexD8_LIN_IRQHandler(void);
    #endif
    #if (LINFlexD_INSTANCE_COUNT > 9U)
    void LINFlexD9_LIN_IRQHandler(void);
    #endif

    /* ISR array for LINFlexD LIN driver */
    extern const isr_t g_LinLINFlexDIsr[LINFlexD_INSTANCE_COUNT];

#endif

#endif
